insert  into profession values (null, 'administrator');
insert  into profession values (null, 'nauczyciel');
insert  into profession values (null, 'ochroniarz');

insert into room values (null, '1A');
insert into room values (null, '4D');
insert into room values (null, '1B');
insert into room values (null, '1D');
insert into room values (null, '2B');
insert into room values (null, '3G');
insert into room values (null, '5A');

insert into subject values (null, 'angielski');
insert into subject values (null, 'matematyka');
insert into subject values (null, 'chemia');
insert into subject values (null, 'plastyka');
insert into subject values (null, 'geografia');
insert into subject values (null, 'informatyka');
insert into subject values (null, 'historia');
insert into subject values (null, 'biologia');
insert into subject values (null, 'wychowanie fizyczne');

insert into employee(name, surname, username, password, age, profession_id) values ('jan', 'nowak', 'janek2', 'Janek11@', 30, 1);
insert into employee(name, surname, username, password, age, profession_id) values ('krzysztof', 'nowakowski', 'krzych2', 'Krzych1@', 29, 2);
insert into employee(name, surname, username, password, age, profession_id) values ('darek', 'Kowalski ', 'darek2', 'Darek11@', 40, 2);
insert into employee(name, surname, username, password, age, profession_id) values ('mariusz', 'Wiśniewski', 'mariusz2', 'Mariusz1@', 37, 2);
insert into employee(name, surname, username, password, age, profession_id) values ('janusz', 'Kowalczyk', 'janusz2', 'Janusz1@', 55, 2);
insert into employee(name, surname, username, password, age, profession_id) values ('paweł', 'Kamiński', 'pawel2', 'Pawel22@', 51, 3);
insert into employee(name, surname, username, password, age, profession_id) values ('adrian', 'Jankowski', 'adrian22', 'Adrian1@', 25, 1);

insert into student (id, name, surname, age, year_Of_Study) values (1, 'Petronille', 'Leadstone', 18, 2);
insert into student (id, name, surname, age, year_Of_Study) values (2, 'Teresina', 'Lafoy', 14, 4);
insert into student (id, name, surname, age, year_Of_Study) values (3, 'Dreddy', 'Maccrea', 16, 2);
insert into student (id, name, surname, age, year_Of_Study) values (4, 'Cass', 'Feldklein', 14, 2);
insert into student (id, name, surname, age, year_Of_Study) values (5, 'Katine', 'Leblanc', 19, 4);
insert into student (id, name, surname, age, year_Of_Study) values (6, 'Lucio', 'Pechold', 15, 1);
insert into student (id, name, surname, age, year_Of_Study) values (7, 'Graham', 'Buckmaster', 18, 4);
insert into student (id, name, surname, age, year_Of_Study) values (8, 'Noella', 'Stener', 16, 3);
insert into student (id, name, surname, age, year_Of_Study) values (9, 'Janina', 'Biaggioli', 14, 1);
insert into student (id, name, surname, age, year_Of_Study) values (10, 'Marja', 'Danford', 16, 2);
insert into student (id, name, surname, age, year_Of_Study) values (11, 'Terrie', 'Menichi', 14, 1);
insert into student (id, name, surname, age, year_Of_Study) values (12, 'Hardy', 'Mation', 17, 4);
insert into student (id, name, surname, age, year_Of_Study) values (13, 'Isobel', 'Denge', 18, 1);
insert into student (id, name, surname, age, year_Of_Study) values (14, 'Elden', 'Buddock', 16, 2);
insert into student (id, name, surname, age, year_Of_Study) values (15, 'Cathie', 'Burnard', 16, 1);
insert into student (id, name, surname, age, year_Of_Study) values (16, 'Oliviero', 'Angric', 15, 3);
insert into student (id, name, surname, age, year_Of_Study) values (17, 'Cara', 'McFee', 15, 3);
insert into student (id, name, surname, age, year_Of_Study) values (18, 'Carrissa', 'Hair', 14, 4);
insert into student (id, name, surname, age, year_Of_Study) values (19, 'Fredi', 'Frangleton', 15, 1);
insert into student (id, name, surname, age, year_Of_Study) values (20, 'Zaria', 'Reyburn', 15, 1);
insert into student (id, name, surname, age, year_Of_Study) values (21, 'Pet', 'Poletto', 16, 4);
insert into student (id, name, surname, age, year_Of_Study) values (22, 'Rey', 'Mantione', 19, 3);
insert into student (id, name, surname, age, year_Of_Study) values (23, 'Hillel', 'Josefsohn', 14, 2);
insert into student (id, name, surname, age, year_Of_Study) values (24, 'Tate', 'Serchwell', 15, 3);
insert into student (id, name, surname, age, year_Of_Study) values (25, 'Eden', 'Wickwarth', 17, 1);
insert into student (id, name, surname, age, year_Of_Study) values (26, 'Mario', 'Enrich', 19, 1);
insert into student (id, name, surname, age, year_Of_Study) values (27, 'Thorndike', 'Tabor', 16, 3);
insert into student (id, name, surname, age, year_Of_Study) values (28, 'Gordy', 'Grumble', 15, 4);
insert into student (id, name, surname, age, year_Of_Study) values (29, 'Aldous', 'Rodder', 19, 2);
insert into student (id, name, surname, age, year_Of_Study) values (30, 'Kesley', 'Bumby', 14, 2);
insert into student (id, name, surname, age, year_Of_Study) values (31, 'Glenda', 'Ponte', 15, 4);
insert into student (id, name, surname, age, year_Of_Study) values (32, 'Janina', 'Burbudge', 17, 1);
insert into student (id, name, surname, age, year_Of_Study) values (33, 'Pierre', 'Clampin', 17, 3);
insert into student (id, name, surname, age, year_Of_Study) values (34, 'Armando', 'Keay', 19, 4);
insert into student (id, name, surname, age, year_Of_Study) values (35, 'Corny', 'Glanert', 18, 4);
insert into student (id, name, surname, age, year_Of_Study) values (36, 'Todd', 'Salter', 15, 2);
insert into student (id, name, surname, age, year_Of_Study) values (37, 'Hermann', 'Milkin', 14, 1);
insert into student (id, name, surname, age, year_Of_Study) values (38, 'North', 'Canaan', 15, 1);
insert into student (id, name, surname, age, year_Of_Study) values (39, 'Dacey', 'Doulton', 15, 1);
insert into student (id, name, surname, age, year_Of_Study) values (40, 'Cathleen', 'Pre', 17, 4);
insert into student (id, name, surname, age, year_Of_Study) values (41, 'Doralynne', 'Dimitriades', 16, 2);
insert into student (id, name, surname, age, year_Of_Study) values (42, 'Heinrick', 'Rubinshtein', 17, 3);
insert into student (id, name, surname, age, year_Of_Study) values (43, 'Brandi', 'Gomes', 15, 1);
insert into student (id, name, surname, age, year_Of_Study) values (44, 'Sayre', 'Dalloway', 17, 3);
insert into student (id, name, surname, age, year_Of_Study) values (45, 'Raeann', 'Penylton', 18, 2);
insert into student (id, name, surname, age, year_Of_Study) values (46, 'Cynthie', 'Alves', 14, 1);
insert into student (id, name, surname, age, year_Of_Study) values (47, 'Tansy', 'Comberbach', 19, 1);
insert into student (id, name, surname, age, year_Of_Study) values (48, 'Renata', 'Huton', 17, 2);
insert into student (id, name, surname, age, year_Of_Study) values (49, 'Olvan', 'Sexton', 18, 3);
insert into student (id, name, surname, age, year_Of_Study) values (50, 'Phip', 'Lapthorne', 19, 3);
insert into student (id, name, surname, age, year_Of_Study) values (51, 'Gennie', 'Horsewood', 17, 4);
insert into student (id, name, surname, age, year_Of_Study) values (52, 'Jenica', 'Eastby', 17, 2);
insert into student (id, name, surname, age, year_Of_Study) values (53, 'Aharon', 'Plaid', 15, 2);
insert into student (id, name, surname, age, year_Of_Study) values (54, 'Gusty', 'McGunley', 18, 4);
insert into student (id, name, surname, age, year_Of_Study) values (55, 'Mercedes', 'Aupol', 18, 4);
insert into student (id, name, surname, age, year_Of_Study) values (56, 'Thomasine', 'Morena', 16, 3);
insert into student (id, name, surname, age, year_Of_Study) values (57, 'Sherilyn', 'Fosserd', 17, 1);
insert into student (id, name, surname, age, year_Of_Study) values (58, 'Aeriela', 'Danilov', 16, 3);
insert into student (id, name, surname, age, year_Of_Study) values (59, 'Karilynn', 'Boxer', 17, 3);
insert into student (id, name, surname, age, year_Of_Study) values (60, 'Corrinne', 'Wallett', 19, 1);
insert into student (id, name, surname, age, year_Of_Study) values (61, 'Justine', 'Domegan', 16, 3);
insert into student (id, name, surname, age, year_Of_Study) values (62, 'Yettie', 'Barsby', 19, 4);
insert into student (id, name, surname, age, year_Of_Study) values (63, 'Bayard', 'Gallihaulk', 14, 2);
insert into student (id, name, surname, age, year_Of_Study) values (64, 'Ray', 'Klaiser', 18, 3);
insert into student (id, name, surname, age, year_Of_Study) values (65, 'Freddi', 'Rosie', 19, 2);
insert into student (id, name, surname, age, year_Of_Study) values (66, 'Lyon', 'Osmond', 17, 1);
insert into student (id, name, surname, age, year_Of_Study) values (67, 'Cooper', 'Rosenbarg', 16, 2);
insert into student (id, name, surname, age, year_Of_Study) values (68, 'Randal', 'Waddams', 18, 3);
insert into student (id, name, surname, age, year_Of_Study) values (69, 'Catherin', 'Norville', 16, 2);
insert into student (id, name, surname, age, year_Of_Study) values (70, 'Xavier', 'Ching', 14, 3);
insert into student (id, name, surname, age, year_Of_Study) values (71, 'Marcus', 'Duncanson', 16, 4);
insert into student (id, name, surname, age, year_Of_Study) values (72, 'Marissa', 'Boneham', 16, 1);
insert into student (id, name, surname, age, year_Of_Study) values (73, 'Bayard', 'Sutterfield', 14, 3);
insert into student (id, name, surname, age, year_Of_Study) values (74, 'Rustie', 'Madgett', 18, 1);
insert into student (id, name, surname, age, year_Of_Study) values (75, 'Rudie', 'Colbeck', 19, 1);
insert into student (id, name, surname, age, year_Of_Study) values (76, 'Christopher', 'Edkins', 14, 3);
insert into student (id, name, surname, age, year_Of_Study) values (77, 'Sherie', 'Lace', 14, 4);
insert into student (id, name, surname, age, year_Of_Study) values (78, 'Whittaker', 'Lorant', 15, 1);
insert into student (id, name, surname, age, year_Of_Study) values (79, 'Katherine', 'Ollerton', 17, 3);
insert into student (id, name, surname, age, year_Of_Study) values (80, 'Celie', 'Smithen', 17, 4);
insert into student (id, name, surname, age, year_Of_Study) values (81, 'Calv', 'MacCurtain', 14, 4);
insert into student (id, name, surname, age, year_Of_Study) values (82, 'Kathryn', 'Sly', 14, 4);
insert into student (id, name, surname, age, year_Of_Study) values (83, 'Wallis', 'Ferrers', 15, 1);
insert into student (id, name, surname, age, year_Of_Study) values (84, 'Elise', 'Breukelman', 14, 2);
insert into student (id, name, surname, age, year_Of_Study) values (85, 'Hendrick', 'Ivermee', 16, 2);
insert into student (id, name, surname, age, year_Of_Study) values (86, 'Shelbi', 'Crosetto', 19, 1);
insert into student (id, name, surname, age, year_Of_Study) values (87, 'Jermaine', 'Cosbee', 16, 1);
insert into student (id, name, surname, age, year_Of_Study) values (88, 'Dolph', 'Matusevich', 16, 1);
insert into student (id, name, surname, age, year_Of_Study) values (89, 'Cicily', 'Denyukin', 15, 1);
insert into student (id, name, surname, age, year_Of_Study) values (90, 'Conway', 'O''Reilly', 19, 1);
insert into student (id, name, surname, age, year_Of_Study) values (91, 'Roby', 'Kloster', 19, 2);
insert into student (id, name, surname, age, year_Of_Study) values (92, 'Fredia', 'Blaze', 18, 4);
insert into student (id, name, surname, age, year_Of_Study) values (93, 'Alla', 'Shere', 15, 4);
insert into student (id, name, surname, age, year_Of_Study) values (94, 'Tildie', 'Kelshaw', 18, 2);
insert into student (id, name, surname, age, year_Of_Study) values (95, 'Kingsley', 'O''Fallone', 16, 3);
insert into student (id, name, surname, age, year_Of_Study) values (96, 'Kendra', 'Woofenden', 16, 3);
insert into student (id, name, surname, age, year_Of_Study) values (97, 'Baxy', 'Stollwerk', 17, 4);
insert into student (id, name, surname, age, year_Of_Study) values (98, 'Antoinette', 'Purchall', 19, 2);
insert into student (id, name, surname, age, year_Of_Study) values (99, 'Leonie', 'Mazzeo', 19, 1);
insert into student (id, name, surname, age, year_Of_Study) values (100, 'Flori', 'Lodder', 16, 2);

insert into lesson (id_subject,id_room,id_employee,start_lesson,end_lesson,lesson_date) values (2,3,4,'08:10:00','09:00:00','2019-10-01');
insert into lesson (id_subject,id_room,id_employee,start_lesson,end_lesson,lesson_date) values (3,2,2,'09:10:00','10:00:00','2019-10-02');
insert into lesson (id_subject,id_room,id_employee,start_lesson,end_lesson,lesson_date) values (5,1,3,'12:10:00','13:00:00','2019-12-06');
insert into lesson (id_subject,id_room,id_employee,start_lesson,end_lesson,lesson_date) values (1,4,5,'13:10:00','14:00:00','2019-10-02');
insert into lesson (id_subject,id_room,id_employee,start_lesson,end_lesson,lesson_date) values (6,2,2,'14:10:00','15:00:00','2019-11-01');
insert into lesson (id_subject,id_room,id_employee,start_lesson,end_lesson,lesson_date) values (9,1,4,'11:10:00','12:00:00','2019-10-12');
insert into lesson (id_subject,id_room,id_employee,start_lesson,end_lesson,lesson_date) values (1,6,5,'09:10:00','10:00:00','2019-11-06');
insert into lesson (id_subject,id_room,id_employee,start_lesson,end_lesson,lesson_date) values (4,7,2,'07:10:00','08:00:00','2019-11-01');